### ISSUE TITLE
Proguard: java.lang.NoSuchMethodError with 2.4.0-alpha6 gradle.

### ISSUE THREAD

**Issue by Quarx2k** [streamsupport/streamsupport#12]
How to reproduce: 
1.  AndroidStudio 2.4 preview 6 +  2.4.0-alpha6,   (Support lambda without retrolambda on any api)
2. 
```
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

```
3. Multidex disabled
4. Proguard:  -dontwarn java8.util.**
5. Code like this StreamSupport.stream().filter().noneMatch;

Cause error:
```
 java.lang.NoSuchMethodError: No static method lambda$makeRef$166(Ljava8/util/stream/MatchOps$MatchKind;Ljava8/util/function/Predicate;)Ljava8/util/stream/MatchOps$BooleanTerminalSink; in class Ljava8/util/stream/MatchOps; or its super classes (declaration of 'java8.util.stream.MatchOps'
java.lang.NoSuchMethodError: java8.util.stream.MatchOps.lambda$makeRef$166
at java8.util.stream.MatchOps.access$lambda$0(MatchOps.java)
at java8.util.stream.MatchOps$$Lambda$1.get(Unknown Source)
at java8.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:245)
at java8.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:211)
at java8.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at java8.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:490)

```
Tested on Android 4.4 and Android 7.1. Both have errors.
Without proguard everything works fine.

Other libs like RX java, have no problems with lambda.

**Comment by stefan-zobel** [comment]
Hi Nickolay,

you shouldn't try to obfuscate or shrink the streamsupport.jar unless you know exactly what you are doing (and have tests that prove that everything still works at runtime). Proguard with default settings doesn't have the slightest clue what it is (not) allowed to do.

If you are using Proguard simply tell it to not touch the "java8" package

`-keep class java8.**`

**Comment by yongjhih** [comment]
Hi Nickolay @Quarx2k ,

For Android, you can just add the following dependency for consuming the proguard config:

```gradle
repositories {
    maven { url "https://jitpack.io" }
}

dependencies {
    compile 'com.github.streamsupport.streamsupport:streamsupport-pro:-SNAPSHOT'
}
```

**Comment by Quarx2k** [comment]
Thanks guys for very fast help!
Issue can be closed now.

But interesting thing, before android gradle 2.4, proguard not obfuscate this methods.

**Comment by Quarx2k** [comment]
Just updated to Android studio 3.0.0 Canary 1 + Android Gradle 3.0-alpha1 + Gradle 4.0-m2;
And again this error. Proguard rules not help.
Retrolambda disabled.
   compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
I can upload sample project, if needed.
```
java.lang.NoSuchMethodError: No static method lambda$makeRef$166(Ljava8/util/stream/MatchOps$MatchKind;Ljava8/util/function/Predicate;)Ljava8/util/stream/MatchOps$BooleanTerminalSink; in class Ljava8/util/stream/MatchOps; or its super classes (declaration of 'java8.util.stream.MatchOps' appears in /data/app/lotsman.kanonier_v2-1/split_lib_dependencies_apk.apk:classes9.dex)
 at java8.util.stream.MatchOps.access$lambda$0(MatchOps.java)
 at java8.util.stream.MatchOps$$Lambda$1.get(Unknown Source)
 at java8.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:245)
 at java8.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:211)
 at java8.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
 at java8.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:490)
```

**Comment by Quarx2k** [comment]
I solved problem by disable retrolambda in StreamSupport lib. Probably it's conflict with android native lambda for 1.6+ java.
Patch: https://pastebin.com/r6kD23Cz

**Comment by stefan-zobel** [comment]
Hi Nickolay @Quarx2k ,

thanks for sharing!

Can you explain how this is related to streamsupport? To me it looks like your tool chain breaks a fully functional jar. Is there something we (streamsupport, i.e. Andrew and me) can do here?

Andrew @yongjhih can you please also take a look at this. Do you see anything that should be done differently?

From my POV the rule is very simple: don't obfuscate / shrink the streamsupport jar. What else could we say / do?

Kind regards,
Stefan

**Comment by Quarx2k** [comment]
Maybe it's not related to our jar. But when i use local jar compiled from source + patch above., everything start work even wtihout proguard rules for java8.**.

I tried our jar with proguard rules:
```
-keepattributes Signature
-keepattributes *Annotation*
-keepattributes InnerClasses
-keepattributes SourceFile
-keepattributes LineNumberTable
-keep class java8.** { *; }
-keep interface java8.** { *; }
-dontwarn java8.**
```
And problem exist only with latest android studio preview and gradle versions.

**But:**
Problem not exist when i addretrolambda in my project.
But i want use native lambdas, because it allow use some other things, like "try with resources" for any api.

**Comment by stefan-zobel** [comment]
Hi Nickolay @Quarx2k ,

I'm not sure what "our jar" refers to. Are you talking about a jar you've build yourself (either from the sources or via jitpack) or does "our jar" refer to the _official_ streamsupport-1.5.4.jar that I've deployed to _Maven Central_ and that is, amongst others, available from _jcenter_?

Note that this site (https://github.com/streamsupport/streamsupport) is only a mirror for the upstream site https://sourceforge.net/projects/streamsupport/ where the coding is done (you can also download the artifacts from there but they are the same that you get from Maven central).

Also note that the "official" streamsupport-1.5.4.jar is a Java 6 Jar file, built with **Maven**, excluding anything even remotely related to Android (no Android Studio, no Gradle, no proguard, no shrinking, no obfuscation, nothing ...).

The recommended way to use streamsupport is to use the official build from Maven Central. If I were you, I wouldn't try to build it myself and if i would do it, I would definitely **not** use Android Studio, Gradle or anything like that (and don't throw in any jar file shrinking technologies).

So again: are you saying that the "official" Jar file from Maven Central doesn't work or are you saying that a Jar file **not** built by me doesn't work?

If the first, I would say that you've unwittingly destroyed the jar in the course of using it in your project (most likely by shrinking it). Other than that I could only imagine a serious bug in the Android Studio build process.

Kind regards,
Stefan

**Comment by Quarx2k** [comment]
Thnaks for answer.  Sorry for misunderstanding.
"Our" means  "net.sourceforge.streamsupport:streamsupport:1.5.4" from repository;

I try explain more detailed.

**Configuration for all variants:**
Proguard disabled/enabled, not make any changes.
Multidex disabled/enabled, not make any changes.
Lib version: net.sourceforge.streamsupport:streamsupport:1.5.4
Android studio 3.0-c1
com.android.tools.build:gradle:3.0.0-alpha1

**Variant 1: _Version from repository_**
**1.** Retrolambda not exist in android project.
App crashed with _java.lang.NoSuchMethodError: No static method lambda$makeRef$166;
**2.** Retrloambda added to android project.
App works fine, no crash.

**Variant 2: _streamsupport.jar compiled by me from github sources_**
Applied patch, which disable retrolambda inside streamsupport.jar.
Everything works fine without include retrolambda in project.

I hope it can help somehow. But yes, it's probably bug of android studio, because Google changed a lot of in build process..

**Comment by stefan-zobel** [comment]
Hi Nickolay @Quarx2k ,

hhm, ok. I understand now. Thanks for the clarification. So, the _official_ build of streamsupport-1.5.4.jar from Maven central doesn't work from within Android Studio 3.0 preview.

That's really weird to say the least. Especially the fact that it works in the presence of retrolambda and does not in its absence. This doesn't really make sense since there is no need to "touch" the Jar in either case.

I can only speculate that the new build process destroys the Jar file (have you tried a debug build or a release build?).

I think you should file a bug in the AOSP bugtracker and then we'll have to wait until the stable AS 3.0 version arrives. If the behavior then still persists feel free to file a new bug (either here or on https://sourceforge.net/p/streamsupport/tickets/).

I think it doesn't make any sense to change anything in Andrew's @yongjhih build settings until the stable version is available (and in that case, it would be Andrew's party).

If you have time, you could try the current 1.5.5-SNAPSHOT build (I'll attach it) to see if that shows the same behavior.

Kind regards,
Stefan
[streamsupport-1.5.5-SNAPSHOT.jar.zip](https://github.com/streamsupport/streamsupport/files/1014323/streamsupport-1.5.5-SNAPSHOT.jar.zip)

**Comment by Quarx2k** [comment]
Thanks. I tested 1.5.5-snapshot.
Same error:  java.lang.NoSuchMethodError: No static method lambda$makeRef$163(Ljava8/util/stream/MatchOps$MatchKind;Ljava8/util/function/Predicate;)Ljava8/util/stream/MatchOps$BooleanTerminalSink; in class Ljava8/util/stream/MatchOps; or its super classes (declaration of 'java8.util.stream.MatchOps'
Lets wait stable release :)

**Comment by stefan-zobel** [comment]
Hi Nickolay @Quarx2k ,

Thanks for trying. In 1.5.5, I've upgraded from retrolambda-1.8 to 2.5.1. I was silently hoping that this could make a difference.

If you file a bug in the AOSP bugtracker please leave a link here.

I've done that myself on several occasions and it really helps (even though it sometimes takes quite some time until they get resolved). Don't hesitate to refer to streamsupport and this issue. Google knows this library and I had my share of conversations with some of their engineers. The only thing you should prepare is a Android Studio test project that reproduces the problem and share this via Google Drive.

Kind regards,
Stefan

**Comment by oasisfeng** [comment]
I've hit a similar error, slightly different exception:
`java.lang.NoSuchMethodError: No static method lambda$and$147(Ljava8/util/function/Predicate;Ljava8/util/function/Predicate;Ljava/lang/Object;)Z in class Ljava8/util/function/Predicates; or its super classes`

Seems like this syntic static method is generated by retrolambda, I guess that's why it is not compatible with native Java 8 support in build tools.

Is it possible to build the streamsupport library with native Java 8 support in Android tool chain instead of retrolambda? It may not fit for non-Android projects, maybe a separate build for Android is a viable option?

**Comment by stefan-zobel** [comment]
Hi @oasisfeng,

I still think this should be reported in the AOSP bugtracker by someone who can reproduce this bug.

I'm very reluctant to experiment with a separate build, especially as long as AS 3.0 hasn't arrived officially.

If I understand you correctly, your idea is to have a separate streamsupport.jar built with the new `desugar` toolchain? Would such a jar be able to be used on old Android versions (e.g. API level 14 or 15) - what's the theory about that?

Even if that ends up working, one of the problems would be that someone has to do all the testing on that separate build (something I'm not sure I have the capacities for). Maybe a streamsupport fork could be a possible approach in such a situation.

In the meanwhile I think our priorities should be:

1) file a bug in the AOSP bugtracker

2) perhaps experiment with a separate build and explore its usability on old Android versions

Personally, I don't even have AS 3.0 installed and I don't think that I'll have the time to do any of these in the near future. So, for the time being, I'll have to rely on the support by someone who is affected by this bug.

Kind regards,
Stefan

**Comment by stefan-zobel** [comment]
FWIW, this one appears to describe the same bug: https://github.com/Yarikx/reductor/issues/30

**Comment by stefan-zobel** [comment]
Found a **P1** bug in the AOSP issuetracker that might be the cause of this weird behavior:

https://issuetracker.google.com/issues/62456849

`desugar` seems to blindly rename the synthetic methods if they start with `lambda$` (appending the owner class name) regardless of whether a reference to that method already exists in the bytecode.

I really hope they'll fix this bug in the final 3.0.0 release.

**Comment by stefan-zobel** [comment]
@oasisfeng and @Quarx2k

This is a bug in the Gradle Java 8 language feature desugaring that is tracked in https://issuetracker.google.com/issues/62456849

See also https://issuetracker.google.com/issues/38414923#comment3 and https://issuetracker.google.com/issues/38414923#comment5

**Comment by oasisfeng** [comment]
@stefan-zobel Thanks for your time investigating this issue.

The reason I'm suggesting fork a separate build for Android desugar tool-chain is also related to the recently introduced capability of desugar that supports interface default & static method natively. This could potentially reduce some of the boilerplate static methods for original interface default methods and support a more Java 8 alike stream chaining style. (e.g. Predicate.and(Predicate))

**Comment by stefan-zobel** [comment]
@oasisfeng 

Hhm, that's an interesting idea. I'm curious: how is this supposed to work on API level < 24? Did you try that?

**Comment by stefan-zobel** [comment]
@oasisfeng and @Quarx2k

OK, so here is a quick & dirty build of the current 1.5.6 snapshot compiled with AS 3.0 Canary 5.

Please let me know if this fixes your immediate problem(s).
[streamsupport_AS3C5-1.5.6-SNAPSHOT.jar.zip](https://github.com/streamsupport/streamsupport/files/1129360/streamsupport_AS3C5-1.5.6-SNAPSHOT.jar.zip)


Note that this is experimental and hasn't yet been subjected to extensive testing, especially not on Android (by that, I mean the AS 3.0 build - not the current state of 1.5.6).

Regards,
Stefan

**Comment by oasisfeng** [comment]
@stefan-zobel  Thanks for the quick build, I'll check it out later today.

In my thorough test, the native support for **interface default method** on pre-24 API level works the similar way as retrolambda, by copying the method body to every implementation class. Since the native tool-chain takes control of the whole build process, it could finally eliminate the inconsistency issue, which surfaces when not all modules depending on interface default method are built with retrolambda.

**Comment by stefan-zobel** [comment]
@oasisfeng

Understood. You've indeed managed to direct my attention to the prospects of a fork. I guess I'll have to play with that idea a tad.

**Comment by stefan-zobel** [comment]
@oasisfeng

In hindsight I believe that the Jar I've uploaded yesterday won't work. I've rewritten it to Java 6 Bytecode (using retrolambda) after the AS compilation step.

The reason for doing that was that I wanted to test it on Java 6 / 7 (succeeded) and also run a quick test on a Marshmallow device using Android Studio 2.3.3 (succeeded).

It only later occurred to me that this will quite likely introduce the exact same problems with AS 3.0 that the original streamsupport.jar reveals.

So here is the original unprocessed (Java 8 bytecode) Jar from the AS 3.0 build. Sorry for the confusion.
[streamsupport_AS3C5-Java8-1.5.6-SNAPSHOT.jar.zip](https://github.com/streamsupport/streamsupport/files/1131819/streamsupport_AS3C5-Java8-1.5.6-SNAPSHOT.jar.zip)

Regards,
Stefan

**Comment by oasisfeng** [comment]
@stefan-zobel Sorry for the delay on testing. I've tested the new build streamsupport_AS3C5-Java8-1.5.6-SNAPSHOT.jar and it works fine thus far. You are right, the library itself should be compiled into java 8 bytecode for the current flawed desugar to process it correctly.

Furthermore, I also forked your build with retrolambda removed and added some interface default methods (e.g. Predicate.and()) to the source, it just works as expected! I can finally use the more chaining-friendly interface default methods in my project.

**Comment by stefan-zobel** [comment]
Hi @oasisfeng Thanks for testing! That's what I've expected. I realized that it shouldn't be necessary to use AS 3 to build the jar(s). In theory, a build with Java 8 `javac` should suffice.

With respect to default / static interface methods: I'm also currently experimenting with this idea. I think I'll have a forked version (different name / package) for Android devs using AS 3 that implements this approach (and changes a few other things internally). I'll let you know when I have something to show.

Thanks for the suggestion!

Stefan

**Comment by oasisfeng** [comment]
@stefan-zobel Cheers~ Looking forward to the new fork! 👍

**Comment by stefan-zobel** [comment]
@oasisfeng and @Quarx2k

OK, here is something to play with:

https://github.com/retrostreams/android-retrostreams/releases/tag/Beta-1

The new package prefix is now "java9.util" instead of "java8.util".

With respect to static / default interface methods the public API should now be identical to the Java 9 API where this is possible (i.e. for all interfaces that have first been introduced in Java 8).

Public static methods and inner classes that served as a replacement for the default / static interfaces methods are gone completely. E.g., no j8.u.s.RefStreams class anymore - all these methods are now in the j9.u.s.Stream interface.

I've had some serious problems with the desugar (Canary 5 & 6) toolchain that prevented doing much on the internal implementation (it's still mostly streamsupport).

The test suite passes successfully on a Pixel C running Marshmallow. Given the problems I've experienced with desugar I don't know if that tells that much.

I'd be seriously interested in your feedback. Just open an issue on https://github.com/retrostreams/android-retrostreams/issues

Regards,
Stefan

**Comment by jdaberkow** [comment]
Hi @stefan-zobel 

I'm looking forward to migrate to the new Android toolchain as well, since that would increase my build speed by far. 

Right now I'm facing exactly this issue but unfortunately I'm not able to use your android-retrostream fork, since I rely on a library that is using streamsupport itself.

However it seems like the streamsupport_AS3C5-Java8-1.5.6-SNAPSHOT.jar.zip you uploaded is able to help me out, but therefore I would also need the cfuture jar.

So I'd like to kindly ask you whether you could either provide me with this one as well or alternatively tell me how I can build it on my own.

Regards
Julian

**Comment by stefan-zobel** [comment]
Hi Julian @jdaberkow

I'll (try to) compile a streamfuture-cfuture.jar this evening and attach it here.
I'll let you know when it is ready. Just wait for 4 / 5 hours. I don't have access to my development workstation right now.

Regards,
Stefan

**Comment by stefan-zobel** [comment]
Hi Julian @jdaberkow

Oh, and btw., before I do that:

Have you tried to use the standard streamsupport-cfuture-1.5.5.jar?

In theory, that should work because there are no `lambda$` methods in it that could be wrongly rewritten by desugar.

All extra components of streamsupport can be compiled with a Java 6 compiler (no need for retrolambda).

The streamsupport main component is the only one that uses lambdas and method references (and therefore needs retrolambda and therefore has `lambda$` methods).

The only thing I could imagine to go wrong is that desugar perhaps treats bytcode version 50 (Java 6) jar files differently. But I don't really believe in that theory.

Please try it out and let me know the result!

Regards,
Stefan

**Comment by jdaberkow** [comment]
@stefan-zobel 

Oh. Interesting. I never thought about that! Let me give it a try.

**Comment by jdaberkow** [comment]
@stefan-zobel 

You are right! As far as I can tell everything works flawlessly. Thank you very much!

Regards
Julian

**Comment by stefan-zobel** [comment]
Hi Julian @jdaberkow

Fine. Let me know if any problems come up.

Another thing:

I don't believe that you have to use AS 3 to compile Java 8 code that uses lambdas / method references when all you want is a jar file that can be used as a library.

A standard Java 8 `javac` should be fine. I compiled all `android-retrostreams` jars on Eclipse, Maven & Java 8 and it works so far.

It's only when the jar files get dexed into an app that desugar's bytecode rewriting magic starts to matter. At least, that's my current understanding.


Regards,
Stefan

**Comment by stefan-zobel** [comment]
@oasisfeng @Quarx2k @jdaberkow

Just wanted to let you know that this desugar bug has been fixed in the meanwhile. See https://issuetracker.google.com/issues/62456849#comment20 (I haven't tested it).

I've released a **Beta-2** of **android-retrostreams** today: https://github.com/retrostreams/android-retrostreams/releases/tag/Beta-2
The problems I had with the Canary 5 / 6 versions of desugar are gone in AS 3 beta 2. So I could back out the workarounds that were necessary in Beta-1. I'm looking forward on working on further internal improvements now.

The Beta-2 release is identical in functionality to streamsupport **1.5.6** (final) which also got released today (https://sourceforge.net/projects/streamsupport/files/1.5.6-stable/).

As always, I'd appreciate any feedback.

Kind regards,
Stefan

**Comment by jdaberkow** [comment]
@stefan-zobel 

Thank you for the information! As for the desugar bug, I can confirm that it has been fixed and that streamsupport now gets desugared correctly.

Greetings
Julian

**Comment by jdaberkow** [comment]
@stefan-zobel 

Besides, you don't know any kind of current workaround to use libraries that are using Java8 features for Android Projects that need to support Android SDK Version 23, do you?

Greetings
Julian

**Comment by stefan-zobel** [comment]
Hi Julian @jdaberkow

Obviously depends on the "feature" you have in mind.

**desugar** supports a lot of language level features (even default / static interface methods and a lot of the new Java 8 annotation stuff).
When you are talking about Java 8 **API**s - no, you are out of luck and need a backport.

However, often a dependency doesn't use that much of new Java 8 APIs. It's often possible to adapt the source code of a dependency to API <= 23 without too much manual work.

Do you have a concrete example in mind?

Greetings,
Stefan

**Comment by jdaberkow** [comment]
Hi Stefan,

thanks for your reply. In fact I was talking about the APIs.

For my Google Tango Smart Home Application [BComfy](https://github.com/openbase/bco.bcomfy) I heavily rely on several stacks of the [BaseCubeOne](https://openbase.github.io/bco/) framework, which are using plenty of Java 8 API stuff.

Therefore I once already ported the packages that I do need in the past. But unfortunately I simply do not have the ressources to maintain these ports and integrate new updates into them, which is why I was hoping for an alternative solution.

But it seems like I have to stay with cherry picking certain commits and besides hoping that I can switch over to API >= 24 soon.

Greetings
Julian
