### ISSUE TITLE
Not support removeIf() method?

### ISSUE THREAD

**Issue by ddrandy** [streamsupport/streamsupport#15]
I have tried using stream support lib like below but failed.
`
    StreamSupport.stream(list)
            .removeIf()
`
So stream support doesn't support this method for now ,right?

**Comment by stefan-zobel** [comment]
streamsupport's Stream interface in the java8.util.stream package has exactly the same methods and behavior as the official Stream interface: https://docs.oracle.com/javase/8/docs/api/java/util/stream/Stream.html

We don't support any additional methods that are not part of the OpenJDK implementation, I'm sorry.
So, since there exists no `removeIf()` method in OpenJDK we also dont't have one.

**Comment by stefan-zobel** [comment]
If you were refering to the `removeIf(Predicate)` default method from the java.util `Collection` interface, we have something similar in `java8.lang.Iterables`:

http://static.javadoc.io/net.sourceforge.streamsupport/streamsupport/1.5.5/java8/lang/Iterables.html#removeIf-java.lang.Iterable-java8.util.function.Predicate-

**Comment by ddrandy** [comment]
Thanks very much.
Now I get it.
`java8.lang.Iterables` works fine.
