### ISSUE TITLE
Restrictive license

### ISSUE THREAD

**Issue by kramer99** [streamsupport/streamsupport#19]
Hi,

First, let me say thanks for backporting these Java 8 features.  I work for a company called Ionic Security, and would like to use streamsupport, but we can't use any libraries licensed under GPLv2.  Would you consider changing the license to something more permissive, ie: LGPL, BSD, or MIT?

**Comment by stefan-zobel** [comment]
Hi Craig,

the license ist **not** GPLv2.

Rather, it's GNU General Public License, version 2, **with the Classpath Exception** (the license that OpenJDK uses).
That's a big difference. Why wouldn't you be able to use streamsupport for anything you want?

Anyway, I can't simply change the license because this code is derived from the OpenJDK code. In fact, it is almost identical in most areas.
So, that wouldn't be legal.

Regards,
Stefan

**Comment by stefan-zobel** [comment]
FWIW, I've once been told by a legal expert that GPL v2 **with the Classpath Exception** is even **less** restrictive than LGPL.

**Comment by kramer99** [comment]
Thanks for getting back so quickly.

I had not heard of the Classpath Exception before.  From my quick googling
on it, it appears that it would be fine for us to use. Will have to run it
past our lawyer first I suppose though.

**Comment by stefan-zobel** [comment]
Do that (and good luck).

The license file is here : https://sourceforge.net/projects/streamsupport/files/1.5.6-stable/LICENSE/download
(in the upstream master project).

Out of curiosity, do you target Android or some older JRE?

Regards,
Stefan

**Comment by kramer99** [comment]
Plain Java 7 for server applications.

**Comment by stefan-zobel** [comment]
Cool, nice to hear (I'm often thinking that I have Android clients only).

Any chance that you'll be running on an IBM JRE? That would require passing a system property to the VM (you can find details here: https://github.com/streamsupport/streamsupport/issues/13

However, Sun / Oracle are fine and get tested regularly from Java 6 - Java 10.

**Comment by stefan-zobel** [comment]
A related issue is:  https://github.com/streamsupport/streamsupport/issues/10
