### ISSUE TITLE
Multiple dex files define Ljava8/util/CollSer;

### ISSUE THREAD

**Issue by maracuja-juice** [streamsupport/streamsupport#23]
I have defined your library in the build.gradle file:
```
    compile 'net.sourceforge.streamsupport:streamsupport:1.6.0'
    compile 'net.sourceforge.streamsupport:streamsupport-cfuture:1.6.0'
    compile 'net.sourceforge.streamsupport:streamsupport-atomic:1.6.0'
    compile 'net.sourceforge.streamsupport:streamsupport-flow:1.6.0'
    compile 'net.sourceforge.streamsupport:streamsupport-literal:1.6.0'
```
And when I try to compile my app I get the following error:
```
Error:Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Ljava8/util/CollSer;
```
A clean of the project didn't help. 

[Related Stackoverflow question](https://stackoverflow.com/questions/48673043/dex-fails-when-using-streamsupport-library)

**Comment by maracuja-juice** [comment]
I switched to the new release that @stefan-zobel mentioned in #22. There's no error with that one.

**Comment by stefan-zobel** [comment]
That's a known bug: https://sourceforge.net/p/streamsupport/tickets/356/ (fixed in the upcoming 1.6.2)

Solution: remove `streamsupport-literal`.

If you need anything from the Java 9 JEP 269 Collections factory methods API (`Lists.of()` and friends) - that has been included in the main `streamsupport` component in release 1.6.0.
Just the names are different: in `streamsupport-literal` it was `java8.util.Lists2`, now it simply is `java8.util.Lists`.

On a side note, I'd recommend using `1.6.1` btw.

Regards,
Stefan

**Comment by maracuja-juice** [comment]
I switched to that one just now. That should be in that repo here, no?
Thanks though.

**Comment by stefan-zobel** [comment]
I'm closing this as a simple workaround is available. Let me know when you have any follow-up problems / questions.

Regards,
Stefan

**Comment by stefan-zobel** [comment]
This repo is only a mirror of the upstream which was on sourceforge until recently: http://sourceforge.net/projects/streamsupport/

I don't operate this mirror ( @yongjhih does ), so unfortunately it's not up-to-date.
See https://github.com/streamsupport/streamsupport/issues/22

The upstream sourceforge project has also moved to GitHub in the meantime: https://github.com/stefan-zobel/streamsupport

That's the new main site for streamsupport. You'll find current binaries there and on Maven Cenrtral / JCenter as well as on the original sourceforge site.

Regards,
Stefan
